export const data = {
  users: [
    {
      "username": "5hahem",
      "biography": "shahem@rekaenergy.co\nTherapist | Astrology | 1/2 cohost @uncancel.culture | LCSW | NYC 🏳️‍🌈",
      "public_email": "its5hahem@gmail.com",
      "last_five_captions": [
        "Hey, Culture! Just a quick update, we’ll see you soon (real soon)! #UncancelCulture",
        "“my therapist said” 😂 #therapy #mentalhealth #community",
        "i know i say it a lot, but sheesh, history is repeating and i hate it #watertowertheory",
        "anything for me and mine lol #uncle #uncleduties",
        "the travelers journey! #therapy #mentalhealth #trauma #traumahealing"
      ]
    },
    {
      "username": "9newsdenver",
      "biography": "Local views, news, and behind-the-scenes. \n9NEWS Denver, CO \nArchived links linkin.bio/9newsdenver\nStory idea? ✉️ newstips@9news.com",
      "public_email": "newstips@9news.com",
      "last_five_captions": [
        "Hello, Spring! 🌷 It's officially Spring in the Northern Hemisphere!",
        "Two detainees have escaped from the Immigration and Customs Enforcement (ICE) facility in Aurora, CO. According to ICE, “local authorities were notified immediately and declined to assist with the search.” The search for Geilond Vido-Romero and Joel Jose Gonzalez is ongoing \n\n#immigration #escape #police #colorado #denver #denvernews #Aurora #ICE",
        "Warren Sapp talks about his love for coaching for the CU Buffaloes' in Boulder. 🏈\n\n#cubuffs #coachprime #9sports #deionsanders #folsomfield",
        "@denvernwsl is planning to build their stadium on the Santa Fe Yards site. I want to find out how you might bike there. #denver #tv #tvnews #colorado #denvernews #bikedenver #bikeden",
        "Spring is almost here! 🌷 The Spring Equinox is Thursday morning in the Northern Hemisphere and as autumn begins in the Southern Hemisphere."
      ]
    },
    {
      "username": "acrojames",
      "biography": "📍Las Vegas\n✨Awakening - Bandit\n🔷America’s Got Talent 2021 \n👱🏻The Ellen Show\n🎪Cirque Du Soleil Crystal 💎\n🏈 SuperBowl Half Time Show - Usher\n⚡️ Voltaire",
      "public_email": "acrojamescollab@gmail.com",
      "last_five_captions": [
        "Positive Impact Movement 2024\nWhat an emotional roller coaster. The amount of love, enthusiasm, trust, communication & community all packed into one room is indescribable. To each & every person who contributed their energy to this weekend, from the bottom of my heart, thank you.\nEach of you contributed in your own special way. The weekend wouldn’t have been the same without you.\nTo our teachers - you are all some of the most knowledgeable & talented people I know. Everyone learned a ton!\nTo our volunteers - you made this festival run seamlessly. We would have fallen apart without you all. You were always there when we needed you.\nTo our Vendors - you brought what you’re most passionate about to the venue & gave tons of people a peek into your world.\nTo the Performers - what a mind blowing experience! Professionals & aspiring pros shared the stage surrounded by so much energy & enthusiasm. Those performances were truly something special.\nTo the @lasvegascircuscenter - this is the Mecca of the circus world. There’s no other place I’d ever want to call home. You supplied a one of a kind venue, run by exceptional staff &the perfect festival mascot (slide 10)\nTo all the Circus Professionals - coming in to coach, inspire & entertain the entire festival is something everyone will remember. Thank you for giving a glimpse into an elite level practice. \nTo our photographers - @jeffcinema and @athenalemos_photo , thank you for the hustle in capturing all the moments.\nTo @amputeeacrobat - thank you for helping run our Adaptive Program. We can’t wait to grow this and make it so the festival is something truly everyone can enjoy.\nNow to my team - @travisbrewer.ninja @nathantsuji @andreas.alfaro , boys we put on one hell of a show. Just three years ago we debuted @positiveimpactmovement on the @agt stage. Now we have created something that everyone can not only watch, but participate in. Our goal was to always bring the spirit of Original Muscle Beach to everyone and it makes me so happy to say, I think we did it. Best teammates I could ever ask for. The amount of trust I have for each of you makes me know we’re going to grow this into one of the biggest things on Earth.🤍",
        "The Pursuit of Happiness\n2 years ago today, @positiveimpactmovement performed on the @ellendegeneres show. I still get happy tears when I think about how this journey has lead me to all of these unforgettable places and moments, standing next to people that I love.\nIt feels like only the beginning.\n“I hope you live a life you’re proud of. And if you find that you’re not, I hope you have the strength to start all over again.”\n-\n#theellenshow #ellen #ellendegeneres #dreamscometrue #endure #pushforward #dontquit #pursuitofhappiness #pursuit #positiveimpactmovement #positiveimpact #acrobatics #weightlifting #weightlift #olympiclifting #cleanandjerk #cleanandpress #handtohand #balance #trust #partneracrobatics #partneracro #acro #acrobatic #acrobalance #cirquedusoleil #cirqueway #cirquegram #cirqueduinsta",
        "Today we get to do what we love most! \n@positiveimpactmovement will be performing in Loveland, Colorado today at the @wolfpackninjas event 2pm!\nIt’s crazy to think of all the absolutely incredible things this crew has accomplished in one year.\nIf you’re wanting to come, tickets are only $30!\n@travisbrewer.ninja @alfaroandreas @nathantsuji \n-\n#agt #americasgottalent #agtauditions #americanninjawarrior #wolfpack #ninja #anw #pim #positiveimpact #positiveimpactmovement #acrobatic #acrobatics #acro #acrobalance #acrodance #acroyoga #acrolove #partneracro #partneracrobatics #circusaroundtheworld #cirqueway #cirquedusoleil #dolby #nbc #peopleareawesome #headstand #barbell #barbells #barbellworkout #olympicweightlifting",
        "Want to learn the Helix? 🧬 \n@besmilegoodlife and I are teaching it in our Dance Lift Intensive at @positiveimpactmovement festival April 11th at the @lasvegascircuscenter \n-\nWe are only 3 weeks away from this year’s festival! With a ton of options for beginners, intermediate and aspiring pros, we have something for you! \n- \nMessage me with any questions!\n-\n#helix #dancelifts #dancelift #acrodance #acro #acroyoga #omb #musclebeach #partneracro #partneracrobatics #spinning #spin #flow #intensive #lasvegas #vegas",
        "Happy Birthday @nathantsuji \nIn the short time we’ve known each other, it really feels like we conquered the world together!\n-\n#happybirthday #birthdayboy #stongman #strongmen #acro #acrobalance #acrodance #acroduo #acrobatics #cirqueway #cirquedusoleil #cirqueduinsta #cirque #circus #circusaroundtheworld #partneracro #partneracrobatics #inversionsmakeyouhot #inversionaddict #inversionjunkie #balance #balanced #balancetraining #trust #trusttheuniverse #trusttheprocess🙏"
      ]
    },
    {
      "username": "adolfoserra",
      "biography": "For black and white @serradolfo\n✨✨✨ New Shop",
      "public_email": "serra.adolfo@gmail.com",
      "last_five_captions": [
        "SEVILLA ❤️me habéis escrito varias personas para realizar un Taller Migrante en el sur así que allá vamos...\n ¡Taller de ilustración para adultos, estudiantes de ilustración y almas creativas! \nDomingo 6 de abril 2025.\nHorario: De 11:00h a 14:00 y de 15:00h a 19:00h (7 horas de taller + 1 hora charla en la hora de comida).\nInfo + Inscripciones: talleresadolfoserra@gmail.com\nPrecio: 150 euros\nPlazas limitadas.\n\nTaller intensivo de 1 día. Exploraremos lo oculto de la ciudad de Sevilla y buscaremos inspiración en los pequeños detalles.\n\nMuchas veces me preguntáis qué llevo en la mochila cuando viajo, qué materiales utilizo o cómo buscar inspiración en lo cotidiano y cómo educar la mirada, la mente o la mano para crear.\n\nEn este taller migrante te daré trucos para romper el bloqueo creativo y jugar con la belleza de lo ordinario. También te explicaré mis técnicas o materiales y recorreremos diversos lugares curiosos de Sevilla para inspirarnos través de una serie de juegos y ejercicios.  El cuaderno será el soporte para experimentar y la ciudad nuestra guía en este taller de formato nómada e intensivo.\n\nIllustration workshop in Seville for adults, illustration students and creative souls!\nSunday 6th abril. \nTimetable: From 11:00h to 14:00h and from 15:00h to 19:00h (7 hours workshop + 1 hour lunchtime talk).\nInfo + Registration: talleresadolfoserra@gmail.com\nPrice: 150 euros\nLimited places.\n\nIntensive 1-day workshop. We will explore the hidden side of the city of Sevilla and look for inspiration in the small details.\n\nMany times you ask me what I carry in my backpack when I travel, what materials I use or how to look for inspiration in the everyday and how to educate the eye, the mind or the hand to create.\n\nIn this migrant workshop I will give you tricks to break the creative block and play with the beauty of the ordinary. I will also explain you my techniques or materials and we will visit different curious places in Seville to get inspired through a series of games and exercises. The notebook will be the place to experiment and the city our guide in this nomadic and intensive workshop.",
        "🌿🌿🌿Imagine a space where illustration blends with the slow rhythm of nature, where the act of drawing becomes a sensory experience, and where inspiration arises from silences, flavors and encounters.\n\nAt @sofia_in_monsaraz , a place where time is diluted in Portugal, I invite you to an exclusive illustration retreat. It is not a conventional workshop, but an immersive experience that vindicates calm, exploration and the pleasure of creating without haste.\n\nOver several days, in a small group, we will share drawing sessions and graphic experimentation, combined with moments of yoga, wine tastings and local cuisine, inspiring walks and conversations around creativity. A retreat designed to nurture both the hand and the eye, to lose oneself in the process and find oneself in the stroke.\n\nIf you are looking for a space to reconnect with your creativity in a unique environment, this retreat is for you.\n\nIllustration Retreat with Adolfo Serra at Sofía en Monsaraz. An encounter between nature, time and landscape.\n\n19 -23 June 2025. Last places available.\nThe workshop will be in English language at Sofía in Monsaraz. Portugal.\nMore info: https://sofiainmonsaraz.com/en/adolfoserra-en/\n📩: info@sofiainmonsaraz.site\n#Illustration #Creativity #ArtisticRetreat #Sofiainmonsaraz #AdolfoSerra\n\nMusic track: Surfing by Zambolino\nSource: https://freetouse.com/music\nRoyalty Free Music for Video (Safe)",
        "Líneas, dibujos, manchas, cuerpos. He dibujado a bailarines en movimiento, en ensayos, en procesos, en el momento de la actuación. Cuerpos en roce, en caricias, en gesto, en encuentro, en música. El cuerpo como un animal, como un instinto, como un relámpago, como arte, como humano, como emoción.\n\nA veces pienso que hay disciplinas que se tocan y que comparten, cambian las herramientas pero se busca la misma esencia. Los bailarines usan su cuerpo, la piel, el gesto y el movimiento como yo uso las acuarelas, el agua o el color. Ambos intentamos contar cosas, expresar ideas, mostrar emociones.\n\nPor eso cuando me propusieron ilustrar la portada de febrero de @eme21mag sobre el nuevo @centro_danza_matadero me pareció que debía bailar con los pinceles, buscar el gesto con la acuarela, crear diversidad y ritmos distintos con el trazo y superponer a personas y movimiento.\n\n******\n\nLines, drawings, stains, bodies. I have drawn dancers in movement, in rehearsals, in processes, at the moment of the performance. Bodies in friction, in caresses, in gesture, in encounter, in music. The body as an animal, as an instinct, as lightning, as art, as human, as emotion.\n\nSometimes I think that there are disciplines that touch and share, the tools change but the same essence is sought. The dancers use their body, skin, gesture and movement as I use watercolors, water or color. We both try to tell things, express ideas, show emotions.\n\nThat’s why when I was asked to illustrate this cover of @eme21mag about the new @centro_danza_matadero it seemed to me that I should dance with brushes, look for the gesture with watercolor, create diversity and different rhythms with the stroke and superimpose people and movement.",
        "¡Colombia ♥️ nos vemos! Con muchas ganas de aprender y compartir. Estaré en @ilustropia.festival de Ilustración, un espacio de encuentro en torno a las artes gráficas y la ilustración, este es un festival en el que convergen formatos interdisciplinares, así como el desarrollo de actividades de ilustración en vivo, feria de publicaciones y talleres de creación.\n\nUn lugar de encuentro y de reflexión en torno a la imagen, el diseño y la creatividad como ejes fundamentales. Del 7 al 11 de mayo en Bogotá. Colombia 🇨🇴 \n\nPor mi parte daré el taller \"El lobo muerde las flores\" de exploración plástica y visual. También charlas y encuentros.\n\nMás info: @ilustropia.festival\n\n¡Gracias a @casatinta.bogota @aecid_es y la Embajada de España en Colombia por la invitación!",
        "MADRID 🥺🥲 me habéis escrito varias personas para realizar un Taller Migrante en Madrid así que allá vamos...\n ¡Taller de ilustración para adultos, estudiantes de ilustración y almas creativas! \nSábado 29 de marzo 2025.\nHorario: De 10:00h a 13:00 y de 14:00h a 18:00h (7 horas de taller + 1 hora charla en la hora de comida).\nInfo + Inscripciones: talleresadolfoserra@gmail.com\nPrecio: 150 euros\nPlazas limitadas.\n\nTaller intensivo de 1 día. Exploraremos lo oculto de la ciudad de Madrid y buscaremos inspiración en los pequeños detalles.\n\nMuchas veces me preguntáis qué llevo en la mochila cuando viajo, qué materiales utilizo o cómo buscar inspiración en lo cotidiano y cómo educar la mirada, la mente o la mano para crear.\n\nEn este taller migrante te daré trucos para romper el bloqueo creativo y jugar con la belleza de lo ordinario. También te explicaré mis técnicas o materiales y recorreremos diversos lugares curiosos de Madrid para inspirarnos través de una serie de juegos y ejercicios.  El cuaderno será el soporte para experimentar y la ciudad nuestra guía en este taller de formato nómada e intensivo.\n\nIllustration workshop in Madrid for adults, illustration students and creative souls!\nSaturday 29 th March. \nTimetable: From 10:00h to 13:00h and from 14:00h to 18:00h (7 hours workshop + 1 hour lunchtime talk).\nInfo + Registration: talleresadolfoserra@gmail.com\nPrice: 150 euros\nLimited places.\n\nIntensive 1-day workshop. We will explore the hidden side of the city of Madrid and look for inspiration in the small details.\n\nMany times you ask me what I carry in my backpack when I travel, what materials I use or how to look for inspiration in the everyday and how to educate the eye, the mind or the hand to create.\n\nIn this migrant workshop I will give you tricks to break the creative block and play with the beauty of the ordinary. I will also explain you my techniques or materials and we will visit different curious places in Madrid to get inspired through a series of games and exercises. The notebook will be the place to experiment and the city our guide in this nomadic and intensive workshop."
      ]
    },
    {
      "username": "amanda.exploring",
      "biography": "Teaching YOU how to travel on points! \nBucket list experiences & luxury travel✈️🌎\n💌ask.amanda.exploring@gmail.com\n36 countries ✈️ credit cards ⬇️",
      "public_email": "ask.amanda.exploring@gmail.com",
      "last_five_captions": [
        "✈️ send to someone you need to stay here with 👀 \n\nFollow @amanda.exploring to learn how to travel the luxury on a budget way with points & miles! \n\nWe had a lot of amazing hotel & resort stays in 2024 but here were the top 5! I chose these 5 all for different reasons including level of service, luxury aspect, uniqueness, location, and beauty! Definitely add these to your points bucket list…you will not regret it! \n\n5. Conrad Osaka - Osaka, Japan\n@conradosaka \n95k Hilton points/night \n\n4. Katara Hills LXR - Doha, Qatar \n@katara.hills \n120k Hilton points/night\n\n3. Calala Island - NiCaribbean, Nicaragua \n@calalaisland \n150k Hilton points/night \n\n2. Park Hyatt Kyoto - Kyoto, Japan\n@parkhyattkyoto \n40k Hyatt points/night \n\n1. Conrad Maldives - Rangali Island, Maldives \n@conrad_maldives \n120k Hilton points/night \n\nI guess it’s obvious I’m a huge @hilton fan 🤪\n\nAre any of these on your list?? If not, which hotels and resorts are?? I need some ideas 👀 \n\n#awardtravel #pointsandmiles #creditcards #creditcard #hilton #hiltonhotels #hiltonhotel #luxuryresorts #luxuryresort #luxurytravel #luxuryhotel #luxuryhotels #luxuryhotelsandresorts #smallluxuryhotels #smallluxuryhotel #smallluxuryhotel #boutiquehotel #boutiquehotels #smallluxuryhotels #maldives #maldivesresorts #luxurydestination #luxurydestinations #luxuryvacation #luxuryvacations #fattravel #luxuryvilla #luxuryvillas #overwatervilla",
        "are you still redeeming points in the travel portal?? \n\n✈️ send to your travel buddy! \n\nwhile in some rare instances it can make sense to redeem points in the portal, IF you really want to maximize value out of your points then you gotta 🛑 stop doing this! \n\nthe 🔑 is transferring your valuable American Express MR points to travel partners. this means… \n\nNOT redeeming your points for gift cards, cash back, or in the travel portal. Transfer instead! \n\nHere’s my process to book an award flight this way:\n\n1. Search on google flights or flightconnections to look up your departure & arrival airports. For this example, I’m searching LAX to MLE. Now I’m going to see which airlines fly direct or with stops. If you know your route also check @upgradedpoints to see all the ways to get there using points and miles. \n\n2. Once you see the airlines, figure out if that airline is in an airline alliance (SkyTeam, Star Alliance, or One World) or not. I see that Qatar Airways (One World alliance) flies direct from LAX to DOH then to MLE and that’s the flight I want.\n\n3. Now, which credit card points do you have that transfer to airlines in that alliance? I have Amex MR pts that transfer to British Airways (shares Avios currency with Qatar Airways).\n\n4. Run award searches to check availability. I use @seatsaero @pointme and PointsYeah to start. Booking far in advance as possible or very close in helps! \n\n5. See how many pts are needed, confirm availability, then transfer the pts and book! I transferred 85k Amex MR to British Airways to book Qsuites ✈️✅\n\nComment “75k” for one of my favorite everyday $95 cards that earns enough points for this flight!!\n……………..\n👋🏼 Hi, I’m Amanda and welcome to my page where I show you that it’s possible to travel the world the luxury on a budget way with credit card points and miles. \n\nbusiness class, QSuites, Qatar, Qatar airways, first class, cheap flights, cheap travel, luxury\n.\n.\n.\n.\n#businessclass #firstclass #firstclassflight #businessclassflyer #luxurytravel #cheapflights #budgettravel #budgettips #travelblogger #funnyreels #travelreel #travelreels #businessclasslounge #points #awardtravel #pointsandmiles #travelgram  #creditcards",
        "✈️ send to someone who wants to stay here!!\n\ncheck out @upgradedpoints (the sponsor of this post) and follow us to stay up to date on points & miles news! Upgraded Points also has a post detailing the new Hyatt category changes taking place in just one week on March 25. Let me know if you’d like the info!\n\nSecrets Resorts going up in category: \n🏝️ Secrets Playa Blanca Costa Mujures\n🏝️ Secrets Cap Cana Resort & Spa\n🏝️ Secrets Maroma Beach Riviera Cancun\n\nI’ll be the first to admit…I used to be anti all-inclusive vacation 🤷🏼‍♀️ that was until Secrets Resorts became bookable with Hyatt points and completely changed my mind about them! Not all all-inclusive resorts are created equal 👀 but Secrets Resorts are some of the most luxury ones. There’s something so relaxing about not worrying about paying for meals or drinks on vacation and I have to say…I’m hooked! \n\nWe recently visited Secrets Maroma Riviera Cancun and were super impressed with the resort—especially the beach and dining! We booked for 35k Hyatt points/night and cash rates were $1200 🤯 here’s all that we experienced: \n\n✨Personalized service and concierge \n✨2 huge beachfront pools with swim up bar \n✨6 restaurants including seafood, steakhouse, unique dishes, Mediterranean, French, and Japanese cuisine \n✨Minibar with water, sparkling waters, beers, and soda filled twice daily \n✨Nespresso coffee and tea bar \n✨Le Labo bath products @lelabofragrances \n✨turn down service with incense \n✨24/7 room service \n✨24/7 specialized coffee shop \n\nWhat’s your take on all-inclusive resorts? Worth it or no?? \n\n.\n.\n.\n.\n.\n#secretsresorts #luxurytravel #pointsandmiles #travelhere #visitmexico #playadelcarmen #allinclusive #allinclusiveresort #allinclusiveresorts #secretsmaroma #secretsakumal #secretsplayamujeres #secretscapcana #mexicotravel #quintanaroo #exploremexico #resortlife #awardtravel #hyatt #travelblogger #travelmore #cheaptravel #traveltips #travelgram #travelreel #travelreels #creditcards #creditcardpoints",
        "✈️send to someone planning a Japan trip! 🇯🇵 \n\nHey 👋🏼 I’m Amanda and I help you plan your trips & save money by booking travel for $0 using credit card points! \n\n🇯🇵 With 10 days in Japan, it was SO hard to figure out where to go and where to skip…and I’ll be honest, Kyoto was not our favorite. We’re glad we visited but likely wouldn’t go back. The place we almost didn’t visit but LOVED was Kawaguchiko, just a 2-hour bus ride from Tokyo. If crowds aren’t your thing…might want to check it out! \n\n✨Fujikawaguchiko mini-guide ⬇️ \n\nHow to get there:\n🚍 take the highway bus from several stations in Tokyo such as Shinjuku or Shibuya (~$16 & cheaper than the train but takes the same amount of time) or the Fuji Excursion train to Kawaguchiko Station \nNote: we actually visited from Osaka by taking a train to Mishima and then catching the highway bus to Kawaguchiko - we bought our tickets on @willer_travel \n\n🎟️ buy your tickets in advance…when the weather looks promising, people will buy up all the tickets the day before \n\nWhere to stay:\nA day trip to Fujikawaguchiko is possible and definitely an option! But if you want more time to chill, I think 1-2 nights is ideal \n\n🏨 Splurge: Ubuya, @fufu_kawaguchiko @fujisan_kaneyamaen & Fuji Onsenji Yumedono\n\nMid-range (still pricey in peak season): @kukuna_official @lakeland_hotel_mizunosato @konansou_official @yamadaya_hotel \n\nBudget: Kawaguchiko Hotel, @lakeside_hotel, Super Hotel Kawaguchiko, Sawa Hotel Fujikawaguchiko \n\nSome of the hotel websites are very difficult to navigate- I highly recommend looking on @bookingcom or @klooktravel \n\nThings to do: \n🍱 Pick up snacks and photo-op at Lawson Kawaguchiko (right by the station when you arrive) \n🏔️ Honcho Street & Fujiyoshida\n🌳 Arakurayama Sengen Park\n⛩️ Oishi Park\n🏞️ Lake Kawaguchiko\n🍜 Hoto Fudo for noodle stew \n🛁 Relax at onsen \n\nIs visiting Mount Fuji area or Kawaguchiko on your list?\n\n#japantravel #japantrip #visitjapan #klook #japanfood #japanphoto #japanlife #japanculture #tokyo #kyoto #kyotojapan #osaka #osakajapan #fuji #fujikawaguchiko #mtfujijapan #kukuna #mountfuji #yamanashi #fujiyoshida #klooktravel #japantips #traveljapan",
        "✈️ send this to a friend you want to go with! \n\n👋🏼 Hi, I’m Amanda and welcome to my page where I show you that it’s possible to travel the world the luxury on a budget way with credit card points and miles. \n\nOur trip to Paris was nothing short of amazing. this is the longest I’ve spent in Paris before and I loved not being rushed to see everything and just getting to walk around every day and see where that took us! we ate a ton of delicious food, visited a couple museums, did some shopping relaxed at the spa. \n\none of my favorites things to do in Paris is sit at a cute cafe and people watch! the experience should definitely have a place on your travel list. here are some favorites: \n\n📍 Carette (pictured here): get the hot chocolate! \n📍 Angelina: also known for hot chocolate \n📍 Café de Flore: super cute cafe \n📍 Café Panis: great location near Notre Dame and Saint Chapelle\n📍 Café Le Buci: great for sandwiches \n📍 Le Recrutement Café: great breakfast spot and IG worthy with an Eiffel Tower backdrop \n📍 Les Deux Magots: very famous (and pricey) but going for the history and a delish coffee is worth it! \n📍 Le Consulat: it is just too cool to sit at the same cafe that Van Gogh & Monet loved. Great steak frites too\n📍 La Fontaine de Belleville: everything is locally sourced \n\nI love using points & miles for airfare & hotels bc that means I get to splurge on dining 🤣 We stayed 3 nights at the Park Hyatt Paris using points from a no annual fee card that earns 75k pts after $6k spend in 6 months!\n\nWho are you taking to Paris with you? \n\n.\n.\n.\n.\n.\n#travelgirl #bucketlist #bucketlisttravel #carette #parislife #visitparis #travelparis #parisfrance #parisienne #thingstodoinparis #mustseeparis #travelblogger #catchflightsnotfeelings #europetravel #eurotrip #parisvibes #seemyparis #paristravelguide #parisguide #budgettravel #travelcouplelife #pointsandmiles #creditcardpoints #travelhack #travelhacks #travelhacking #traveltips #hiddengems"
      ]
    },
    {
      "username": "artoftravesuras",
      "biography": "𝙰𝚛𝚝𝚒𝚜𝚝𝚊 𝚋𝚊𝚜𝚎𝚍 𝚒𝚗 𝚂𝙵, 𝙲𝙰\n➭𝐧𝐞𝐱𝐭 𝐬𝐡𝐨𝐩 𝐮𝐩𝐝𝐚𝐭𝐞: 2/15 11am pt\n➭𝚌𝚞𝚜𝚝𝚘𝚖 𝚍𝚘𝚕𝚕 𝚘𝚛𝚍𝚎𝚛𝚜 𝚝𝚑𝚛𝚘𝚞𝚐𝚑 𝚙𝚊𝚝𝚛𝚎𝚘𝚗\n➭𝚒𝚗𝚚𝚞𝚒𝚛𝚒𝚎𝚜— 𝚊𝚛𝚝𝚘𝚏𝚝𝚛𝚊𝚟𝚎𝚜𝚞𝚛𝚊𝚜＠𝚐𝚖𝚊𝚒𝚕.𝚌𝚘𝚖",
      "public_email": "artoftravesuras@gmail.com",
      "last_five_captions": [
        "Using this post to answer other frequently asked questions in the caption and comments☺️\n\n🗝️All in stock items are on my website—shoptravesuras.com\n\n🗝️If something is sold out or you don’t see it in my shop anymore, I sometimes do restocks that I post about here on my social media pages\n\n🗝️If you’d like to support my art and receive extra monthly perks, I have a Patreon that you can subscribe to. One of the perks is access to commissions/custom orders. I don’t offer commissions outside of Patreon due to the current demand🖤 \n\nYou can find all this in my bio as well✨\n\nFeel free to let me know if you have any other questions! I’ll keep this video pinned✨\n\n#dollmaker #ooakdolls #customdoll #dollcustom #spookyart",
        "Surprisingly I only completed about 6 commissions since January— but it’s been a busy busy time!! Thank you so much to these wonderful clients for giving me the chance to create something special for them :) there’s soooo many fun ones coming up too I can’t wait to share! \n\n#dollmaker #dollcustom #coralinedoll #customplush #ooakdoll",
        "Sending my favorite doll off in style— thank you so much Alex for giving her a home! Decorating envelopes gives me the perfect amount of closure for a project, especially when they mean a lot to me. I challenged myself so much with this doll (and even made two because I knew I wasn’t going to part with her) and the response she’s gotten has really filled me with joy and confidence— thank you!\n\nSpecial thanks to @hereticparfum for gifting me the new Nosferatu perfume! Not even the packaging is going to waste🖤🥀\n\n#ooakdoll #packaging #envelopeart #nosferatu #vampirecore #artdoll #gothart",
        "March rewards— inspired by some of my favorite horror stories!! This month tiers 3+ get a bonus mini print and the clay club item is an eyeball bookmark!!✨\n\nSpecial shout out to @monikakimauthor for giving me a new appreciation for eyes after reading her novel last year, the inspo behind some of the rewards this month! 👀\n\nIf you’d like to receive monthly stickers, prints, mini sculptures, or just some behind the scenes on my work feel free to check out the different tiers I offer <3 \n\n#illustration #procreate #tomie #junjiito #stickermail #patreon #horrorfiction",
        "Five artists one prompt— a Nosferatu collaboration🥀\n\nSwipe through to see how each artist was inspired by the film to create something for this project— we had so much fun getting to share our work with eachother throughout the process and wanted to bring you in a bit more too. Being an artist that exists mostly in the online space can be a bit lonely, so working on a project like this really opened us up creatively! \n\nIf you aren’t already familiar with these folks you can find them tagged above or below and as always thank you for your support!!\n\n@mimsvictims \n@artoftravesuras \n@soulsofbeldam \n@lucyswurld \n@cachurroart \n\n#nosferatu #ooakdolls #ellenhutter #costumedesign #dollmakers #artdolls #mixedmediaartist #sculpting"
      ]
    },
    {
      "username": "_beneg_",
      "biography": "🎬 Quality | Smooth | Cinematic\n🔄 Rotate your phone & enjoy\n✨ Edits that pull you in\n👇 Follow for more & free presets",
      "public_email": "benegedit@gmail.com",
      "last_five_captions": [
        "I’ve noticed an increase in inquiries in my Instagram messages along the lines of “How to achieve better video quality?” or “What effects to use for higher quality?” and similar questions. Therefore, I would like to urge you to reflect on this trend without taking it as an attack.\n\nI’ve observed that many editors offer their color corrections (CC) for purchase, aiming to make money. Often, I’ve encountered instances where these CCs were misused and distributed further, with some editors then asking others to provide their settings for free.\n\nI believe the best solution is to learn these effects yourself. Personally, I’ve never sold my edits, dedicating all my time to improving my videos. However, when someone asks me to share this information, I honestly have no interest.\n\nI’m a working individual, and I believe that if you desire something, you should learn how to achieve it yourself.",
        "#assasinscreedshadows #gaming #aesthetic #assasinscreed #samurai #assasin #japan",
        "The Electric State: A Journey Into the Unknown… ⚡🤖 Are You Ready?\n\n#TheElectricState #ElectricStateMovie #Netflix #NetflixMovie #SciFiAdventure #MillieBobbyBrown #ChrisPratt #StanleyTucci #KeHuyQuan #AnthonyMackie #ScienceFiction #Dystopian #RobotCompanion #Cyberpunk #FilmEdit #MovieAesthetic #FuturisticVibes #Aesthetic #FYP #ForYou #ForYouPage #Trending #Viral #MovieEdit #instagood #Explore #robot",
        "#deathstranding2 #gaming #aesthetic #playstation"
      ]
    },
    {
      "username": "berecker",
      "biography": "▫️single dad, dog dad\n▫️ex-pastor, writer\n▫️be curious, not judgmental ♥️\n📍Raleigh",
      "public_email": "contactbrianrecker@gmail.com",
      "last_five_captions": [
        "Jesus was not more concerned with protecting supposed “Biblical truth” than he was with protecting PEOPLE. Jesus always put people before dogma. \nAccording to Jesus, the whole purpose of religion is to lead us into LOVE. When our religious rules do not lead to greater human flourishing, we don’t keep the dogmatic rule at the expense of people! This is why Jesus said humans were not made for the Sabbath command- the Sabbath was made for humans. \nJesus taught us to change for the sake of the person in front of us- that’s the best reason to change.\nNothing is more arrogant and dangerous than someone who thinks that they already have all the answers, and that encountering diverse perspectives should not change their settled, rigid beliefs.\nOur worldview should always be shifting as we encounter diverse voices- we should always be widening to enlarge the scope of our love.\nFor example, a few months ago I read an incredible book by a queer black woman called “The Day God saw me as Black.” The author had a chapter about what it was like to live in her body. She wrote about how her body is often “defeminized” because of her size, making her both invisible and hyper visible. As someone with an entirely different embodied experience, it was so good for me to contemplate life in a different body, especially one that encounters marginalization I know nothing about. \nThis is the opposite of toxic. This is how our hearts are enlarged.  \n.\n.\n.\n#empathy #christiannationalism #deconstruction #exvangelical #spirituality #jesus #inclusion",
        "Without even realizing it, Driscoll’s vision for white heteronormative masculinity actually excludes the person he believes he is worshiping. His spirituality has very little to do with Jesus. It’s about dominance. Straight, white, male dominance. I wish he was the exception, but if you scratch the surface of many white evangelical churches, this is the message.\nWhat if following Jesus was not just about believing he was God as a ticket to heaven in the afterlife, but actually about a way of love in this life? What if it was about the spirituality of Jesus, not the supremacy of being a Christian? If that is appealing to you, you may like my substack, where I’m writing about the life and ministry of Jesus, without the dogma. Comment “beloved” below and I’ll DM you a subscribe link— it’s free!\n. \n. \n#deconstruction #exvangelical #christiannationalism #whitesupremacy #jesus #spirituality",
        "hi 👋 ☺️ I got some new followers from my last few reels, and based on the comments I think some of them are just there to remind me how hot hell is 🙃 But I’m assuming some of you resonate with my journey, and I’m happy to have you along for the ride! I’ve made lots of friends and connections on this silly little app, and it’s nice to be reminded of people walking a similar journey. Much love ✌️♥️\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n#parenting #singledad #dadlife #singledads #singleparent #raleigh #raleighnc #wfh #workingfromhome #mullet #mullethair #tattoos #handtattoo #tattooeddad #menwithtattoos #tattooedmen #dogsofinstagram #doglife #deconstruction #theology #gaychristian #queertheology #christianity #church #hell #universalism #religioustrauma",
        "Being told to surrender your sexuality every time you experience it is not holiness, it’s harm. It leads to disintegrated sexuality and self hatred. The problem has never been being gay. The problem is a theology that treats heterosexual love as superior, and teaches queer people to hate the way God made them.\nGod loves people and wants their flourishing, so that means God hates these ideas that harm our beloved queer siblings. 💖💖\n.\n.\n#deconstruction #exvangelical #spirituality #jesus #christiannationalism #pride #lgbt",
        "This and a new season of Temptation Island.\n.\n.\n.\n#dating #relationships #divorce #coparenting #raleigh #detroit #brunch #politics"
      ]
    },
    {
      "username": "blog_cinemaniac",
      "biography": "Por Thiago Barata\nCinema para amantes de cinema.\nConteúdo 100% original.\n+ de 50k nas redes\nParcerias: thiagobarata87@gmail.com ou via direct",
      "public_email": "thiagobarata87@gmail.com",
      "last_five_captions": [
        "Qual desses filmes mexeu com você?\n\nHoje eu preparei uma lista \"pesada\". Aproveitando que O Nevoeiro reapareceu no catálogo da Netflix, eu fiz uma lista com 10 filmes que vão te destruir emocionalmente enquanto você assisti. Todos os filmes dessa lista mexeram de verdade comigo. Me impactaram. Me emocionaram. Me angustiaram em algum nível. \n\nSão filmes que nos desafiam enquanto público. Testam o nosso vínculo de empatia. Nos apresentam o mundo como ele é. Seja através da fantasia do cinema de gênero, seja através da realidade do drama. Nem só de escapismo pode viver o cinema. Às vezes precisamos tomar esses choques de realidade. \n\nO filme da capa é \"Pieces of Woman\", um filme dilacerante sobre o efeito do luto na identidade de uma mulher. \n\nGostou? Compartilhe com os amigos e diga qual desses filmes te impactou em algum nível.",
        "Esse filme vai te emocionar!\n\nEu só dei nota 10 para dois filmes em 2023. A Menina Silenciosa foi um deles. Com distribuição da Imovision, o filme chegou aos cinemas com uma história lindíssima sobre a linguagem do afeto na formação de uma criança. \n\nVeja nos cinemas!\n\nNota: 10/10\n\nGostou? Compartilhe!\n\nTags: #ameninasilenciosa #filmeseséries #imovision #filmesdrama #filmesdramáticos",
        "Quem viu essa maluquice de filme?\n\nEu não acredito que a Netflix adicionou esse filme maluco no seu catálogo. Um filme sobre relacionamentos como você nunca viu. Se prepare... O Lagosta vai mexer com a sua cabeça.\n\nNota: Veja e tire as suas conclusões!\n\nGostou? Compartilhe e marque um amigo fã de filmes malucos.\n\nTags: #olagosta\n#dicasnetflix #indicaçãodefilmes #filmescult",
        "Quem viu esse filmaço na Netflix?\n\nEu não acredito que esse filme reapareceu na Netflix com uma história real inacreditável. Se você não viu, corre para ver porque ele é envolvente, tem um elenco fantástico e vai te surpreender.\n\nA Grande Aposta (2015)\nNota: 10/10\nOnde: Netflix\n\n#dicasnetflix #filmesdecomédia #indicaçãodefilmes",
        "Qual dessas reviravoltas te surpreendeu?\n\nHoje eu preparei uma lista daquelas que vocês amam. Só com filmes com reviravoltas que alugaram um triplex na minha cabeça. Daquelas que impactam. Todos os filmes dessa lista permaneceram comigo. E com vocês?\n\nO filme da capa é \"Os Suspeitos\", de Denis Villeneuve, um thriller policial inquietante sobre os limites morais ultrapassados por dois homens à procura de duas meninas desaparecidas. O final desse filme...\n\nE o que falar de \"Incêndios\"? É indigesto! Na busca por respostas, dois irmãos mergulham no passado da mãe e encontram algo inacreditável. \n\n\"O Convite\" me impactou pela forma com que aborda um sentimento de angústia que paira pelo mundo. Uma reunião entre amigos ganha contornos bizarros quando as intenções dos anfitriões são reveladas. E que revelação...\n\n\"O Nevoeiro\" então nem se fala... Quando uma névoa isola um grupo de sobreviventes num mercado, as tensões do mundo real são encapsuladas num conto sombrio e dilacerante de Stephen King - brilhantemente adaptado por Frank Darabont. \n\nE vamos com uma dobradinha Park Chan Wook. Começando por \"Decisão de Partir\", um romance que nasce de uma investigação policial e revela os segredos por trás de uma relação movida pela sedução. Que final é esse?\n\nO segundo é \"A Criada\" e esse... Só digo uma coisa: se prepare! Um filme provocante, cheio de reviravoltas, que mergulha na perspectiva feminina num thriller que se renova a cada ação. \n\n\"A Vila\" meio que dispensa comentários. É o meu filme favorito de M. Night Shyamalan e muito pela forma com que ele cria uma atmosfera imersiva e fantástica sem tirar os pés da realidade. \n\nMichael Haneke é inevitável. Se você der o play num filme dele, você vai terminar impactado. E em \"Caché\" uma família ameaçada por um estranho se vê em apuros e obrigada a entender porque se colocaram naquela situação. \n\nEu adoro esse filme! \"The Perfection\" mergulha na rivalidade entre duas musicistas para ir além dela e repercutir o impacto de um mundo patriarcal no destino delas. É absurdo!\n\nE vou fechar a lista com Christopher Nolan. \"Seguinte\" segue os passos de um homem atraído por uma mulher, mas envolvido em algo que ele não poderia imaginar."
      ]
    },
    {
      "username": "candisgrace",
      "biography": "LifeStyle Specialist 😎 || President of Marketing Agency @TheBrandGroupLA as seen on @forbes ||Lover of God 🙏🏾| Charity: @browngirlluxe",
      "public_email": "info@thebrandgroup.la",
      "last_five_captions": [
        "Real Friendship and Respect Gives Credit and Love where it’s Due 🌹 The Love and Respect that @badassboz and I carry for one another is something so Special to Me. Thank You for Always Trusting Me with Not Only Your Brand and Business but with Your Heart and vulnerability in Sisterhood. We have cried on each other shoulders and we have laughed until we cannot stand up straight. I’m so proud of you for what you accomplished on this tour all while in the middle of your own loss and tough moments in life. YOU ARE A CHAMPION!!! 🏆🏆🏆 My Own Personal CMO 🥰🥰\n\nA special moment captured by : @j_shwahh \n\nOn site: New York City, @dreamdowntown \n\n@thebadassworkshop - 5 MAJOR CITIES BABBYYYY!!",
        "I Be Matching with My Homies 🤞🏾🩸\n\n@jarule \n@pro_fes73",
        "WOW!!! NEW YORK , You Really Showed Out for @badassboz and @thebadassworkshop at @dreamdowntown by @taogrouphospitality 🌹\n\nI mean what a treat to experience the energy of New York and how well they loved, received and really Got their Whole Life during Boz amazing presentation of it being “our season” and “our season to bloom like the flowers”. 🌺 So many people expressing life changing stories and more. \n\nIt’s always an honor to be called in by My Own Personal CMO @badassboz of My life to produce her impactful events. What she wants, she gets!!! Thank you for choosing the experts at @thebrandgroupla to bring your visions to life Time and time again. \n\nTo My Right Hand @chefjeffdidit , our magic together is something unexplainable. Thank you for being one of the absolute best people I know in my world. \n\nTo the infamous team @dreamdowntown and @taogrouphospitality , you guys ARE ROCKSTARS!!!! 🫶🏾\n\n📷: @imrich_too",
        "We’re Never Coming Undone 🤞🏾🖤\n\n@myfabolouslife \n@bkrube",
        "An exhilarating Performance in @hadestown , featuring My @haileyfkilgore 🫶🏾🫶🏾🫶🏾 What a Night to Experience this Show , @nickarrington1 and I had the best time. A Must See if you’re in New York. 🌹"
      ]
    },
    {
      "username": "carlcrusher",
      "biography": "Carl the Crusher and the Crusher Crew! \nExploring mysteries UFOs & Paranormal \n🏜 Southern Utah • Nevada • Arizona 🛸\n#mystery #travel #ufo #paranormal",
      "public_email": "clickplaystudiosinc@gmail.com",
      "last_five_captions": [
        "Horseshoe Bend and Cliff Dwellers",
        "If the UFO whistleblower claims are true, then we should be able to prove it. \n.\n.\n#ufo #uap #eggufo #disclosure #history #discovery #psionic #telepathy",
        "Is Summoning UFOs bad? In all of the recent news about UAP disclosure, remote viewing, and \"summoning\" UFOs is treated like demonology. This suppression of human consciousness has existed for thousands of years, and we need to drop the prejudice around it.",
        "Gnomes Spotted In Southern Utah\n\n#gnomes #folklore #elves #utah #duende #sighting #skinwalker #goblins #paranormal #elfontheshelf"
      ]
    },
    {
      "username": "cinema.bestt",
      "biography": "اخبار سينما\nنقد و معرفي فيلم\nمصاحبه \nدیالوگ و فوتوشات",
      "public_email": "hesam.hbc3@gmai.com",
      "last_five_captions": [
        ".\nشوخی های همیشگی و بامزه جیمی کیمل با مت دیمون بازیگر موفق هالیوودی در مراسم اسکار سال ۲۰۱۷\nبا زیرنویس اختصاصی",
        ".\nرفتار و برخورد جالب کیانو ریوز ستاره بازیگری هالیوود که محبوبیت فوق العاده ای دارد با پسر بچه طرفدارش\nبا زیرنویس اختصاصی",
        ".\nآل پاچینو ابر ستاره دنیای سینما با همون روحیه شوخ و جذاب در ۸۴ سالگی\nبا زیرنویس اختصاصی",
        ".\nآموزش فارسی سخت به کونان اوبراین مجری مشهور آمریکایی\n😂😂😂😂\nبا زیرنویس اختصاصی",
        ".\nواکنش هریسون فورد به سوال خبرنگاری که اخرین روز کاری خود را سپری کرد\n😂😂😂😂\nبا زیرنویس اختصاصی"
      ]
    },
    {
      "username": "cinemablend",
      "biography": "One of the most popular entertainment sites, covering movies, TV and celebrity news. Read more at CinemaBlend.com",
      "public_email": "contact@cinemablend.com",
      "last_five_captions": [
        "Raise your hand if you’re still thinking about the “Materialists” trailer A24 dropped yesterday ✋\n\n#a24 #materialists #pedropascal #dakotajohnson #chrisevans #movie #celebrity",
        "Gal Gadot got her Star on the Hollywood Walk of Fame this week, and her friend/former director Patty Jenkins had some lovely things to say about the “Wonder Woman” and “Snow White” actress \n\n(🎥: Getty Images)\n\n#galgadot #pattyjenkins #wonderwoman #snowwhite #evilqueen #hollywoodwalkoffame #celebrity #movie #superhero #disney #dc",
        "Gwyneth Paltrow is spilling all the details about her upcoming A24 movie “Marty Supreme” with Timothée Chalamet. After the Goop CEO revealed what she told intimacy coordinators on set, she gave her honest opinion on working with the “Dune” actor. \n\n(📸: Getty Images)\n\n#martysupreme #gwynethpaltrow #timotheechalamet #A24 #movie #celebrity",
        "Grip it and rip it! Netflix’s “Happy Gilmore 2” teaser trailer just dropped and we can already tell this sequel is going to be our new happy place.\n\n#happygilmore2 #happygilmore #netflix #adamsandler #benstiller #juliebowen #movie",
        "Disney’s live-action remakes have been hit or miss, but early screenings of “Snow White” are seeing extremely positive reviews so far. While this is just the first wave of reaction, people seem blown away by Rachel Zegler’s portrayal of Disney’s first princess alongside Gal Gadot’s evil stepmother and queen.\n\n#snowwhite #liveactionsnowhite #disney #liveactionremake #rachelzegler #galgadot #movies #disneyprincess"
      ]
    },
    {
      "username": "cinemadrive_",
      "biography": "Page about all things Cinema.\n-\nPartnerships: contactcinemadrive@gmail.com",
      "public_email": "contactcinemadrive@gmail.com",
      "last_five_captions": [
        "To prepare, Matthew McConaughey created a four hundred fifty-page analysis, the “Four Stages of Rustin Cohle,” to study his character’s evolution over the course of the story.\n\n📺: True Detective S1\n\nFollow @cinemadrive_ for more content!",
        "The many faces of Gary Oldman 🎭 What is your favourite performance by him? 💭\n\nFollow @cinemadrive_ for more content!",
        "New Line Cinema executives originally balked at the film’s ending, but Brad Pitt refused to make the film if the ending was changed. 📦\n\n🎥: Se7en (1995)\n\nFollow @cinemadrive_ for more content!",
        "Happy Friday, Cinephiles! 🕺\n\nWhich dance is your favourite? 💭\n\n1. Anya Taylor-Joy in The Queens Gambit\n2. Tom Cruise in Tropic Thunder (2008)\n3. Christopher Walken in Weapon of Choice music video by Fatboy ft. Bootsy Collins\n4. Ana de Armas in Deep Water (2022)\n5. Omar Sy in The Intouchables (2011)\n6. Robert Downey Jr. in OnePlus commercial \n7. Tobey Maguire in Spider-Man 3 (2007)\n\nFollow @cinemadrive_ for more content!",
        "The director and the filmography 🎥\n\nWhich directors filmography is your favourite? 💭\n\nFollow @cinemadrive_ for more content!"
      ]
    },
    {
      "username": "descontroladamente",
      "biography": "🌌 | filmes, séries, doramas e muito mais!\n🔔 | ative as notificações para não perder nadinha\n🧚🏻‍♀️ | indicações incríveis + stories interativos",
      "public_email": "igdescontroladamente@gmail.com",
      "last_five_captions": [
        "🎬 Filme: Lilo & Stitch @descontroladamente⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\ntags #lilo #liloestitch #stitch #liloandstitch",
        "🎬 Novela: Rebelde @descontroladamente⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\ntags #rebelde #robertapardo #miacolucci #dulcemaria #anahi #rbd",
        "🎬 Reality: De Férias com o Ex @descontroladamente⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\ntags #defériascomoex #gabiprado #zoo #defériascomoexbrasil #realitys",
        "⟨ Filme: Wicked ⟩⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⠀⠀⠀\n⠀⠀⠀\n📺 Onde assistir: -⠀\n🎬 Sinopse: Na Terra de Oz, uma jovem chamada Elphaba forma uma improvável amizade com uma estudante popular chamada Glinda. Após um encontro com o Mágico de Oz, o relacionamento delas logo chega a uma encruzilhada.⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n🔍 Mais informações:⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\nDuração: 2h 40m⁣⁣⁣⁣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\nClassificação: 10 anos⁣⁣⁣⁣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n💟 → Mais tirinhas do filme: #igdwicked | #igdfilmes⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n🔎 Tags | #arianagrande #wicked",
        "⟨ Série: Com Carinho, Kitty | 2x01 ⟩⁣⁣⁣⁣⁣⠀\n⠀\n📺 Onde assistir: Netflix⠀⠀⠀⠀⠀⠀\n🎬 Temporadas: 2⠀⠀⠀⠀⠀⠀\n⁣⁣⁣⁣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n🔍 Mais informações:⠀⠀⠀⠀⠀⠀⠀\nDuração: 30 minutos⁣⠀⠀⠀⠀⠀⠀⠀⠀\nClassificação: 12 anos⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⁣⁣⁣⁣⁣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n💟 → Mais tirinhas da série: #igdcomcarinhokitty | #igdséries⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n🔎 tags: #comcarinhokitty #annacathcart #sangheonlee #xokitty"
      ]
    }
  ]
}